@startuml
skinparam titleBorderRoundCorner 15
skinparam titleBorderThickness 2
skinparam titleBorderColor DeepSkyBlue
skinparam titleBackgroundColor MidnightBlue
skinparam titleFontColor white
title Osbert Diagrama de Clases 
class Galeria{
    vector Cuadros
    +Cuadro buscarCuadros(int año, String autor)
    +Cuadro buscarSimilares(int id)
    +void remover Cuadro(int id)
    +void agregarCuadro(Cuadro C)
    
}
class Cuadro {
    -int id
    -String titulo
    -String artista
    -String fecha
    -float precio
    +int getId()
    +float getPrecio()
    +String getTitulo()
    +String getArtista()
    +String getFecha()
    +float calcularPrecio();
}
class Reporte{
    -String transaccion
    -Cuadro c
    -float Precio
    -String fecha
    +get()
    +set()
}
Reporte *-- Cuadro
Galeria *-- Cuadro
@enduml

